---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: staging
  namespace: staging
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:s*
spec:
  releaseName: staging
  chart:
    git: git@github.com:sureshamk/hello-flux-helm.git
    path: charts/hello
    ref: staging
    # label: stagingsync
  valuesFrom:
  - chartFileRef:
      # path within the helm chart (from git repo) where environment-prod.yaml is located
      path: overrides/environment-staging.yaml # mandatory
      # If set to true successful retrieval of the values file is no
      # longer mandatory
      optional: true