---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: dev
  namespace: dev
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.hello-flux: glob:dev*
spec:
  releaseName: dev
  chart:
    git: git@github.com:sureshamk/hello-flux-helm.git
    path: charts/hello
    ref: master
  values:
    hello:
      name: api
      image: sureshamk/hello-flux:dev-d1d5ae8
      imagePullPolicy: IfNotPresent
      ingress:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
          nginx.ingress.kubernetes.io/rewrite-target: /
        path: /
        hosts:
        - api.example.com

    # Dependencies values
    adminer:
      host: admin.example.com
