---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: dev
  namespace: dev
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:v*
spec:
  releaseName: dev
  chart:
    git: git@github.com:sureshamk/hello-flux-helm.git
    path: charts/hello
    ref: master
  valuesFrom:
  - chartFileRef:
      # path within the helm chart (from git repo) where environment-prod.yaml is located
      path: overrides/environment-dev.yaml # mandatory
      # If set to true successful retrieval of the values file is no
      # longer mandatory
      optional: true