hello:
  name: api
  image: sureshamk/hello-flux:dev-d1d5ae8
  imagePullPolicy: IfNotPresent
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
      nginx.ingress.kubernetes.io/rewrite-target: /
    path: /
    hosts:
    - api.example.com

# Dependencies values
adminer:
  host: admin.example.com    