api:
  name: api
  image: sureshamk/hello-flux:latest
  imagePullPolicy: IfNotPresent
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
      nginx.ingress.kubernetes.io/rewrite-target: /
    path: /api
    hosts:
    - api.example.com

# Dependencies values
dependencies:
  minio:
    enabled: false