version: 1
commandUpdated:
  generators:
    - command: generator_command
  updaters:
    - containerImage:
        command: image_updater_program
      policy:
        command: policy_updater_program