apiVersion: ENC[AES256_GCM,data:SKQ=,iv:SOZ3/FJwq0EQySw04h4wLy2EY8BOi+8MtojGoRsmHso=,tag:JW1MrgBPXE5s7sFEWJPkEA==,type:str]
kind: ENC[AES256_GCM,data:qeDe8w2j,iv:Ze5IIG3YWgAdHvW8ZjQKVNUT65ekLWPCkPUk2DqREWk=,tag:w1dN00o5VcGEQ1jmlGdkXA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:p7xzoeM1faI=,iv:JUSQp5i43D7/vduItUsjLg2IAESicpZFo3KFTuY5FoE=,tag:NcNwXiVV13VKdByo2RP4fg==,type:str]
type: ENC[AES256_GCM,data:BQJWQT/E,iv:iO7MLTIixdMGqiL0PEX9YP8xgrOata9Ue1yvHD6e3to=,tag:KrXwqPiDV76kwQlHCwGF0w==,type:str]
data:
    key: ENC[AES256_GCM,data:+H5w204AQlI=,iv:tLHGL6RYbqOMhMNdJsf0VAV2oV56Jq7HXf32N87CXqE=,tag:dmQ0QMTG2pi3ShYqPAzZPA==,type:str]
    #ENC[AES256_GCM,data:asCI5nsV5i9TZpSVvYOOPT/1,iv:bBPxUmYCjHHNFbyw8jYthB3t58bZwja/M2oyVwWtLFo=,tag:JmWo9MQayV/hUN31b8PsSg==,type:comment]
sops:
    kms:
    -   arn: arn:aws:kms:ap-southeast-1:609249146283:key/41918855-c602-4227-af5d-30288b3fd4bb
        created_at: '2020-03-10T13:22:16Z'
        enc: AQICAHgomvwZz4E07aT9rTgoWtPqJpN5gMw0XL+z/VQAfwKpfQGA3tp772w3TnV0Nf9NKq5jAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMCbwPCphpm/ydN3u5AgEQgDvUDahAkO10rRkwShrbh69IB8MIsxRf+wGvNw92i0bITu86vgcFCFJ1fccZ6k0wWKLSJNtQUFG/9ai6iQ==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-03-10T13:22:17Z'
    mac: ENC[AES256_GCM,data:nrPOFkau3Cspvn4rwGJE0qL4TZl5yBGmCwTSJFA4ZtYDclgKYkGapqoiy+or74bcQSWzkIFlJNgSSxNy0ZUx7UhyFRKUSiIKjabWeNnRqCgMi7SGiO4rbWM3BCLZdzZTRgD90Dfi0QkQvaf4+XmiZHC1Wv/HEWbpPeAx+PjryoM=,iv:+HlYfx/BVFBiE+k68xvZjvEtx3PlkyPugfYIlCtVjHM=,tag:Mh5G6LYvgcFO7KQEYudpIw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.5.0
---
apiVersion: ENC[AES256_GCM,data:6Hs=,iv:H2o90Hek37qBP/AULUWfogLBN7gGY14CO5Y2d7Ko3Ng=,tag:t7WeJ4QEyqkWKNCNqJNcXA==,type:str]
kind: ENC[AES256_GCM,data:+kObRQNv,iv:wTdC6y0osm9RKFTFh8Bm67Yb5OWXTYym6omXaWsNED4=,tag:cw64lwEs2D4qbIWpQm19Kw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Lj8/h8I1Hpml,iv:IbsArTbokRc+AjAVFmQXrFVy5+63T6wMvtoLG0vgAf4=,tag:Q0s+uMmtkBZQshEUKjImjw==,type:str]
type: ENC[AES256_GCM,data:ZB/yLTrS,iv:jHjYsCB+JWYTKFqRZHzvls4h1O2cZJydWszqL20rWpU=,tag:1kuel6ACZMqbr8ancuBOrQ==,type:str]
data:
    key: ENC[AES256_GCM,data:3ZY9V6ZTBDc=,iv:SR1DIugk6mNwUDfTbXainnQ9MvgTLAe3N9cc2NWuS40=,tag:/EDpmfr2AuB7ne7vzM89gA==,type:str]
    #ENC[AES256_GCM,data:VfVw9ItO3m/Ld7B99ru5uHwf,iv:hsrWC8SyDYo8/K8dG8vM1+66sCIg4UerfYNX1MwRuNY=,tag:NaXt6jCM4y555fXr78wg3Q==,type:comment]
sops:
    kms:
    -   arn: arn:aws:kms:ap-southeast-1:609249146283:key/41918855-c602-4227-af5d-30288b3fd4bb
        created_at: '2020-03-10T13:22:16Z'
        enc: AQICAHgomvwZz4E07aT9rTgoWtPqJpN5gMw0XL+z/VQAfwKpfQGA3tp772w3TnV0Nf9NKq5jAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMCbwPCphpm/ydN3u5AgEQgDvUDahAkO10rRkwShrbh69IB8MIsxRf+wGvNw92i0bITu86vgcFCFJ1fccZ6k0wWKLSJNtQUFG/9ai6iQ==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-03-10T13:22:17Z'
    mac: ENC[AES256_GCM,data:nrPOFkau3Cspvn4rwGJE0qL4TZl5yBGmCwTSJFA4ZtYDclgKYkGapqoiy+or74bcQSWzkIFlJNgSSxNy0ZUx7UhyFRKUSiIKjabWeNnRqCgMi7SGiO4rbWM3BCLZdzZTRgD90Dfi0QkQvaf4+XmiZHC1Wv/HEWbpPeAx+PjryoM=,iv:+HlYfx/BVFBiE+k68xvZjvEtx3PlkyPugfYIlCtVjHM=,tag:Mh5G6LYvgcFO7KQEYudpIw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.5.0
---
apiVersion: ENC[AES256_GCM,data:cMI=,iv:OXacFHHPhjZ090CB0RD++X3MSYMTJ8gS7xQlSTOc6iU=,tag:x51xPmcSpo7IcK9w2wSPyA==,type:str]
kind: ENC[AES256_GCM,data:rK4T2QI7,iv:wSGd5dNN7qLkMWWhW1GW0mu62jwaCmlslUlf6AxM4Og=,tag:3gpHDd4CWSZGNzYa3uvfMQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ViobB93IZ+5x,iv:YUNCgSyRX4t1OTWsjx156st6CdvYfqVaV8lxbqsghaA=,tag:aDg/oqDIuP6q5yRl62BDMw==,type:str]
type: ENC[AES256_GCM,data:uqLXaHLb,iv:sRORfhrlWVeAxWUY29G7KbvYkeAu82nDJVsz9NmPn58=,tag:fE2kp9kevY3QCulpDgWJuQ==,type:str]
data:
    key: ENC[AES256_GCM,data:D8meiDJCZZs=,iv:lvOVnFsAAH+wSotLrOmBSyxiDWV8p6AQ8y9GslH+MOE=,tag:K5te6wEhXPcGyDW7ba2zMQ==,type:str]
    #ENC[AES256_GCM,data:0SKCM6zQDXRBdnsdJb7YMQYz,iv:L/s7Hf0EXsQKdNiQ4ouMtFnWnHL7SQx9t8FSUJrMC+k=,tag:9NT1RpY2PkwWNbAMW0LqrA==,type:comment]
sops:
    kms:
    -   arn: arn:aws:kms:ap-southeast-1:609249146283:key/41918855-c602-4227-af5d-30288b3fd4bb
        created_at: '2020-03-10T13:22:16Z'
        enc: AQICAHgomvwZz4E07aT9rTgoWtPqJpN5gMw0XL+z/VQAfwKpfQGA3tp772w3TnV0Nf9NKq5jAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMCbwPCphpm/ydN3u5AgEQgDvUDahAkO10rRkwShrbh69IB8MIsxRf+wGvNw92i0bITu86vgcFCFJ1fccZ6k0wWKLSJNtQUFG/9ai6iQ==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-03-10T13:22:17Z'
    mac: ENC[AES256_GCM,data:nrPOFkau3Cspvn4rwGJE0qL4TZl5yBGmCwTSJFA4ZtYDclgKYkGapqoiy+or74bcQSWzkIFlJNgSSxNy0ZUx7UhyFRKUSiIKjabWeNnRqCgMi7SGiO4rbWM3BCLZdzZTRgD90Dfi0QkQvaf4+XmiZHC1Wv/HEWbpPeAx+PjryoM=,iv:+HlYfx/BVFBiE+k68xvZjvEtx3PlkyPugfYIlCtVjHM=,tag:Mh5G6LYvgcFO7KQEYudpIw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.5.0
