---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux-ui
  namespace: flux
spec:
  releaseName: flux-ui
  chart:
    git: https://github.com/sureshamk/flux-ui.git
    path: flux-ui
    ref: master
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.flux-ui: glob:dev*
  values:
    image:
      repository: sureshamk/flux-ui
      tag: dev-e7a6c46
      #  pullPolicy: Always
      pullPolicy: IfNotPresent
    config:
      END_POINT: "http://flux:3030/"
      BASE_API: "/api/"
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
      hosts:
      - host: fluxui.sk8test.tk
        paths:
        - /
