---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux-ui
  namespace: flux
spec:
  releaseName: flux-web
  chart:
    git: https://github.com/sureshamk/flux-ui.git
    path: flux-ui
    ref: master
  values:
    image:
      repository: sureshamk/flux-ui
      tag: latest
      #  pullPolicy: Always
      pullPolicy: IfNotPresent
    config:
      END_POINT: "http://flux:3030/"
      BASE_API: "/api/"
    ingress:
      enabled: true
      hosts:
        - host: fluxui.sk8test.tk
          paths:
            - /